FROM s/libruntime:latest

# Create a working directory app under the root folder in the "samiislam/lib:latest" image
WORKDIR /app

# Copy only the items starting with myconsole from the console folder of the current project to the
# /app folder in the image
COPY /console/myconsole* ./

# Copy only the items starting with myconsole from the console folder of the current project to the
# /app/consoleonly folder in the image just to show that only the myconsole* items are indeed copied
RUN mkdir /consoleonly
COPY /console/myconsole* /consoleonly/

ENTRYPOINT ["dotnet", "myconsole.dll"]